# Generated by Django 6.0.5 on 2026-06-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.item')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
