# Generated by Django 6.0.5 on 2026-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_book_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='detail_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
