# Generated by Django 6.0.5 on 2026-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemtype_detail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='detail_type',
            field=models.CharField(default='OTHERS', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(default='Others', max_length=50, unique=True),
        ),
    ]
