# Generated by Django 6.0.5 on 2026-06-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_itemtype_detail_type_alter_itemtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinyl',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.item')),
                ('artist', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('discs', models.IntegerField(blank=True, null=True)),
                ('rpm', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
